### ISSUE TITLE
[BUG] Little bug from new tab command complete

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3799]
![image](https://user-images.githubusercontent.com/13446881/84557297-846e1b80-ad32-11ea-842a-775cebed4484.png)

**Comment by derech1e** [comment]
Strange, for me it works in the latest nightly Dev-Build:
![image](https://user-images.githubusercontent.com/39240736/84565160-8bfbe780-ad67-11ea-89b8-c5c6586e422e.png)

**Comment by Teals53** [comment]
Let me test again

edit: bcs u r using i not ı xD

**Comment by Teals53** [comment]
i try that again from latest build and its still same 
![image](https://user-images.githubusercontent.com/13446881/84569697-40f6ca00-ad91-11ea-8eca-b8d8bd8f8323.png)

but just for inventory things other ones working good

**Comment by kawaiinekololis** [comment]
working for me too

**Comment by derech1e** [comment]
> i try that again from latest build and its still same
> ![image](https://user-images.githubusercontent.com/13446881/84569697-40f6ca00-ad91-11ea-8eca-b8d8bd8f8323.png)
> 
> but just for inventory things other ones working good

That's wired. Especially since it also works for @kawaiinekololis.

**Comment by derech1e** [comment]
> Let me test again

I need further informations. Can you share a video, wherein you show when this bug occurs.

**Comment by Teals53** [comment]
I will make one asap

**Comment by Teals53** [comment]
https://youtu.be/MYxejMVI2vo

@derech1e

**Comment by derech1e** [comment]
> https://youtu.be/MYxejMVI2vo
> 
> @derech1e

It is really hard to reproduce your issue. I have fixed some other bugs i found and partially recoded the render check.

Download the Dev Build here: https://easyupload.io/uacrf9 and test it again.

**Comment by Teals53** [comment]
> > https://youtu.be/MYxejMVI2vo
> > @derech1e
> 
> It is really hard to reproduce your issue. I have fixed some other bugs i found and partially recoded the render check.
> 
> Download my Dev-Build here: https://easyupload.io/uacrf9 and test it again.
> 
> @Teals53

this build have same problem too

**Comment by derech1e** [comment]
> > > https://youtu.be/MYxejMVI2vo
> > > @derech1e
> > 
> > 
> > It is really hard to reproduce your issue. I have fixed some other bugs i found and partially recoded the render check.
> > Download my Dev-Build here: https://easyupload.io/uacrf9 and test it again.
> > @Teals53
> 
> this build have same problem too

I have no idea, where this bug come from. Can you maybe send me your LiquidBounce-1.8 config folder?

**Comment by Teals53** [comment]
> > > > https://youtu.be/MYxejMVI2vo
> > > > @derech1e
> > > 
> > > 
> > > It is really hard to reproduce your issue. I have fixed some other bugs i found and partially recoded the render check.
> > > Download my Dev-Build here: https://easyupload.io/uacrf9 and test it again.
> > > @Teals53
> > 
> > 
> > this build have same problem too
> 
> Okay I have no idea, where this bug come from. Can you maybe send me your LiquidBounce-1.8 config folder and your latest client log from LB?
> @Teals53

its doesnt matter its still happening in resetted folder also where can i find log

**Comment by Teals53** [comment]
also i find different bug

![image](https://user-images.githubusercontent.com/13446881/84604612-e730f580-ae9f-11ea-9471-c2d7a6dec27f.png)

**Comment by Teals53** [comment]
also i found different bug too why latest page commands not listed for this first letter

![image](https://user-images.githubusercontent.com/13446881/84604694-848c2980-aea0-11ea-8163-8c8401a9c54c.png)

**Comment by derech1e** [comment]
I cant reproduce any of your bugs. Idk, for me everthing works fine:
https://streamable.com/f99jpj

**Comment by derech1e** [comment]
> also i find different bug
> 
> ![image](https://user-images.githubusercontent.com/13446881/84604612-e730f580-ae9f-11ea-9471-c2d7a6dec27f.png)
> also i found different bug too why latest page commands not listed for this first letter
> 
> ![image](https://user-images.githubusercontent.com/13446881/84604694-848c2980-aea0-11ea-8163-8c8401a9c54c.png)

I cant reproduce any of your bugs. Idk, for me everthing works fine:
https://streamable.com/f99jpj
@Teals53

**Comment by Teals53** [comment]
well i delete my .minecraft and try again with latest build but still same i dont understand why i happen this bugs and u cant reporouduce those things do you have a discord ?

**Comment by derech1e** [comment]
> well i delete my .minecraft and try again with latest build but still same i dont understand why i happen this bugs and u cant reporouduce those things do you have a discord ?

Yeah, i have Discord.

**Comment by Teals53** [comment]
Teals53#1508

**Comment by derech1e** [comment]
> Teals53#1508

I added you

**Comment by Teals53** [comment]
> > Teals53#1508
> 
> I added you

send me a pm dude i forgot

**Comment by Teals53** [comment]
its causing of optifine

**Comment by Teals53** [comment]
so when im use lb with optifine this bugs is happening but when im use lb without optifine its working good

**Comment by Teals53** [comment]
@derech1e

**Comment by derech1e** [comment]
I'll wait until the first stable cross-version is released, before I continuing to look at the bug. If it's really an Optifine problem, I think it will be maybe difficult to fix it.

**Comment by Teals53** [comment]
okk ^^

**Comment by Teals53** [comment]
![image](https://user-images.githubusercontent.com/13446881/91647721-a68c5580-ea66-11ea-8515-f43ba5d84139.png)
maybe its causing of ı if i start with i no problem

**Comment by derech1e** [comment]
So, I found the issue that causes this wired shifting. The problem is located in the optifine Fontrenderer class.

**Look:**
The renderChar method returns the char width as a float: 
![renderChar_opt](https://user-images.githubusercontent.com/39240736/91655891-871c1980-eab4-11ea-8da7-c37716f2871e.PNG)

This float is then added (to put it simple) to the X pos of the cursor:
![renderChar_renderStringAtPos_opt](https://user-images.githubusercontent.com/39240736/91655893-871c1980-eab4-11ea-85c9-31b266b910b8.PNG)

But when the tabcomplete draws the examples, you can only get the width of the String as an int:
![getStringWidth](https://user-images.githubusercontent.com/39240736/91655889-86838300-eab4-11ea-98b3-b2ef6a2be071.PNG)

so there are this small decimal numbers that make this thing worse. Basically it only needs to be cast to an int. But as the Fontrenderer from optifine dont uses the same methods...
![int_cast](https://user-images.githubusercontent.com/39240736/91655890-871c1980-eab4-11ea-9317-3f90fd2e0ac5.PNG)

I will be fix it, but at the moment I have not that much time. And the other thing is, what is that letter "ı". I can't even type it on my keyboard. What Language is that? Is that an "i" or idk, it doesn't even have a point above the line.
@Teals53

**Comment by Teals53** [comment]
turkish letters like ı ö ü ç ş 
U can write I so its just capital ı
